#ifndef APPLICATION_ACTION_H
#define APPLICATION_ACTION_H

enum AppAction {
    NONE = 0,
    CLOSE = 1,
    CAMERA_SET_ORBIT_LEFT,
    CAMERA_UNSET_ORBIT_LEFT,
    CAMERA_SET_ORBIT_RIGHT,
    CAMERA_UNSET_ORBIT_RIGHT,
    CAMERA_SET_ORBIT_UP,
    CAMERA_UNSET_ORBIT_UP,
    CAMERA_SET_ORBIT_DOWN,
    CAMERA_UNSET_ORBIT_DOWN,
    CAMERA_SET_ROTATE_CL,
    CAMERA_UNSET_ROTATE_CL,
    CAMERA_SET_ROTATE_CCL,
    CAMERA_UNSET_ROTATE_CCL,
    CAMERA_SET_ZOOM_IN,
    CAMERA_UNSET_ZOOM_IN,
    CAMERA_SET_ZOOM_OUT,
    CAMERA_UNSET_ZOOM_OUT,
    CAMERA_INCREASE_ROTATE_SPEED,
    CAMERA_DECREASE_ROTATE_SPEED,
    CAMERA_RESET,
    CLICK_SPHERE,
    UNCLICK_SPHERE,
    MOVE_MOUSE,
    DRAW_MODE_ROTATE,
    WINDOW_RESIZE,
};

#endif //APPLICATION_ACTION_H
